### ISSUE TITLE
微博的新API获取到的似乎是置顶动态

### ISSUE THREAD

**Issue by nenekodev** [sparanoid/a-soul#5]
我这边运行之后日志提示时间戳都是几个月前的动态，对照发现可能是获取到了置顶内容

可以参见db中的记录：https://github.com/nenekodev/A-SOUL-Wecom-Notifier/blob/database/db/db.json

**Comment by sparanoid** [comment]
https://github.com/sparanoid/a-soul/blob/master/packages/core/src/index.js#L1429-L1435 这里其实有做判断，但是你那边没生效是吗？

**Comment by nenekodev** [comment]
> https://github.com/sparanoid/a-soul/blob/master/packages/core/src/index.js#L1429-L1435 这里其实有做判断，但是你那边没生效是吗？

好像是的 因为我的代码只是把发送消息的部分改了 这些判断的部分没有动过

**Comment by sparanoid** [comment]
[这里](https://github.com/sparanoid/a-soul/commit/ee3b03170fd683365ddfcadf6430b31a5f550841#diff-25426a917b53575c0f0efc5674ee70c4d2c8671f9ade4f9d994db43c9552302bR1415-R1420) 应该是修复了，改动有点大，顺便把每次两个请求改为一个请求了

**Comment by nenekodev** [comment]
ok🥰 我这边测试一下🥰
